package delivery

import (
	_ "embed"
	"net/http"

	"github.com/dwikynator/minato"
)

// specJSON is the Swagger 2.0 JSON spec baked into the binary at compile time.
// The file is generated by `make proto` and committed to the repository.
// Embedding it means:
//   - Zero disk I/O per request.
//   - The deployed binary and its spec are always in sync.
//   - No contract/ directory needs to be present at runtime.
//
//go:embed embed/openapi.swagger.json
var specJSON []byte

// docsHTML is the Swagger UI page. It is a self-contained HTML string that
// loads the Swagger UI bundle from jsDelivr CDN and points it at /openapi.json.
// No npm build, no static assets to manage.
const docsHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>core-auth API Docs</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url:            '/openapi.json',
      dom_id:         '#swagger-ui',
      presets:        [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
      layout:         'BaseLayout',
      deepLinking:    true,
      filter:         true,
      tryItOutEnabled: true,
    });
  </script>
</body>
</html>`

// docsHTMLBytes is the pre-allocated HTML bytes.
// Avoid converting the const string on every request.
var docsHTMLBytes = []byte(docsHTML)

// RegisterDocsHTTPHandler registers:
//   - GET /openapi.json  — raw Swagger 2.0 spec (cache 1 h; spec regenerates rarely)
//   - GET /docs          — Swagger UI explorer
//
// Both handlers serve pre-computed byte slices with zero per-request allocations.
func RegisterDocsHTTPHandler(s *minato.Server) {
	s.Router().Get("/openapi.json", serveSpec)
	s.Router().Get("/docs", serveDocs)
}

// serveSpec serves the embedded Swagger 2.0 JSON spec.
//
// Cache-Control is set to 1 hour: the spec changes only when protos are
// regenerated and the binary is redeployed, so a short public cache is safe.
func serveSpec(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "public, max-age=3600")
	w.WriteHeader(http.StatusOK)
	w.Write(specJSON)
}

// serveDocs serves the Swagger UI HTML page.
//
// Cache-Control is set to 1 day: the HTML is a constant string that only
// changes when the Swagger UI CDN version is bumped in code.
func serveDocs(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=86400")
	w.WriteHeader(http.StatusOK)
	w.Write(docsHTMLBytes)
}
